---
title: "Future Exercise"
---

```{r}
library(dslabs)

# only run the next command interactively, not in a script
# help(gapminder)  
# get an overview of data structure
str(gapminder)

# get a summary of data
summary(gapminder)

# determine the type of object gapminder is
class(gapminder)
```

```{r}
africandata <- subset(gapminder, continent %in% "Africa") #subsetting data for african countries

# get an overview of data structure
str(africandata)

# get a summary of data
summary(africandata)

# determine the type of object gapminder is
class(africandata)

```

```{r}
infant_mortality_data <- data.frame(africandata$infant_mortality, africandata$life_expectancy) #making a dataframe for infant mortality
population_data <- data.frame(africandata$population, africandata$life_expectancy) #making a dataframe for infant mortality
```

```{r}
# get an overview of data structure
str(infant_mortality_data)

# get a summary of data
summary(infant_mortality_data)
```

```{r}
# get an overview of data structure
str(population_data)

# get a summary of data
summary(population_data)
```

```{r}
#ploting infant mortality vs life expectancy
plot(infant_mortality_data$africandata.infant_mortality, infant_mortality_data$africandata.life_expectancy)
```

```{r}
 #ploting population vs life expectancy
 plot(log(population_data$africandata.population, base = 2), population_data$africandata.life_expectancy)
 
# In both plots, streak patterns occur because each country contributes multiple times across different years and they tend to grow.
```

```{r}
missingyears <- is.na(infant_mortality_data$africandata.infant_mortality)

missingyears_df <- data.frame(africandata$year, missingyears)

plot(missingyears_df)

```

```{r}
africandata_year2000 <- subset(africandata, year %in% 2000)

# get an overview of data structure
str(africandata_year2000)

# get a summary of data
summary(africandata_year2000)
```

```{r}
#replotting only year 2000
plot(africandata_year2000$infant_mortality, africandata_year2000$life_expectancy)

plot(log(africandata_year2000$population, base = 2), africandata_year2000$life_expectancy)
```

```{r}
#lm base on year 2000

fit1 <- lm(life_expectancy ~ infant_mortality, data = africandata_year2000)
summary(fit1)

fit2 <- lm(life_expectancy ~ population, data = africandata_year2000)
summary(fit2)
```